//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cassettes
    {
        public int C_cod { get; set; }
        public string C_Name { get; set; }
        public string C_sub { get; set; }
        public Nullable<double> C_len { get; set; }
        public int C_A_cod { get; set; }
    
        public virtual Authors Authors { get; set; }
    }
}
