//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class interview
    {
        public int IntervewNum { get; set; }
        public Nullable<int> Id_Intervoewer { get; set; }
        public Nullable<int> id_interviewee { get; set; }
        public string Date_intervew { get; set; }
        public string interviewFORrole { get; set; }
        public Nullable<int> isSucceed { get; set; }
    }
}
