//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class masterEntities : DbContext
    {
        public masterEntities()
            : base("name=masterEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Authors> Authors { get; set; }
        public virtual DbSet<Candidates> Candidates { get; set; }
        public virtual DbSet<Cassettes> Cassettes { get; set; }
        public virtual DbSet<city> city { get; set; }
        public virtual DbSet<departments> departments { get; set; }
        public virtual DbSet<Emeployees> Emeployees { get; set; }
        public virtual DbSet<interview> interview { get; set; }
        public virtual DbSet<nurse> nurse { get; set; }
        public virtual DbSet<patients> patients { get; set; }
        public virtual DbSet<room> room { get; set; }
        public virtual DbSet<shiftt> shiftt { get; set; }
        public virtual DbSet<MSreplication_options> MSreplication_options { get; set; }
        public virtual DbSet<spt_fallback_db> spt_fallback_db { get; set; }
        public virtual DbSet<spt_fallback_dev> spt_fallback_dev { get; set; }
        public virtual DbSet<spt_fallback_usg> spt_fallback_usg { get; set; }
        public virtual DbSet<spt_monitor> spt_monitor { get; set; }
    }
}
