//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class patients
    {
        public string IDpatient { get; set; }
        public string NAMEpatient { get; set; }
        public Nullable<System.DateTime> BIRTHDAYpatient { get; set; }
        public string ADRESS { get; set; }
        public Nullable<System.DateTime> ADRESSpatient { get; set; }
        public Nullable<int> CODEroomPATIENTS { get; set; }
        public Nullable<int> CODEcity { get; set; }
        public string ILLNESSpatient { get; set; }
    
        public virtual city city { get; set; }
        public virtual room room { get; set; }
    }
}
