//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class shiftt
    {
        public int CODEshift { get; set; }
        public string CODEnursesSHIFT { get; set; }
        public Nullable<int> CODEroomSHIFT { get; set; }
        public System.DateTime BEGINhourSHIFT { get; set; }
        public System.DateTime ENDhourSHIFT { get; set; }
    
        public virtual nurse nurse { get; set; }
        public virtual room room { get; set; }
    }
}
